controller_manager:
  ros__parameters:
    update_rate: 50

    joint_position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_position_controller:
  ros__parameters:
    joints: [r_sho_pitch]
